# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeV1_0',
            fields=[
                ('CollegeId', models.AutoField(primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StateV1_0',
            fields=[
                ('StateId', models.AutoField(primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='collegev1_0',
            name='StateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeData.StateV1_0'),
        ),
    ]
