# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collegeData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userv1_0',
            fields=[
                ('Uid', models.AutoField(primary_key=True, serialize=False)),
                ('EmailId', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(max_length=255)),
                ('RegisterTime', models.DateField(blank=True, null=True)),
                ('CollegeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeData.CollegeV1_0')),
                ('StateId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeData.StateV1_0')),
            ],
        ),
    ]
